In [2]:
import pandas as pd
import numpy as np

In [4]:

customers = pd.read_csv("output/dim_customers.csv")
products = pd.read_csv("output/dim_products.csv")
categories = pd.read_csv("output/dim_categories.csv")
stores = pd.read_csv("output/dim_stores.csv")
suppliers = pd.read_csv("output/dim_suppliers.csv")

sales_orders = pd.read_csv("output/fact_sales_orders.csv")
sales_order_items = pd.read_csv("output/fact_sales_order_items.csv")
inventory = pd.read_csv("output/fact_inventory.csv")
inventory_movement = pd.read_csv("output/fact_inventory_movement.csv")

In [19]:
customers.head()

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
0,1,Ramesh Verma,ramesh.verma495@outlook.com,7239980629,Pune,Female,2019-04-16,New
1,2,Deepak Gupta,deepak.gupta505@rediffmail.com,9452970852,Delhi,Male,2022-06-15,Premium
2,3,Vihaan Kapoor,vihaan.kapoor995@outlook.com,9244739576,Kanpur,Female,2022-08-02,New
3,4,Priya Singh,priya.singh209@gmail.com,8786250248,Indore,Male,2022-02-01,New
4,5,Sanjay Joshi,sanjay.joshi872@outlook.com,8700894595,Bengaluru,Other,2020-01-30,New

In [20]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 6104 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        6104 non-null   int64
 1   customer_name      5939 non-null   str
 2   email              6104 non-null   str
 3   phone              6104 non-null   str
 4   city               6104 non-null   str
 5   gender             6104 non-null   str
 6   registration_date  6104 non-null   str
 7   customer_segment   6104 non-null   str
dtypes: int64(1), str(7)
memory usage: 381.6 KB

In [8]:
customers[customers["phone"].str.contains(r"\+91" , na=False)]

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
23,24,Sai Desai,sai.desai108yahoo.com,+91-7655181723,Ludhiana,Male,2023-07-28,Regular
50,50,Priya Malhotra,priya.malhotra548@outlook.com,+91-9901714208,Nashik,Male,2022-05-13,Regular
151,150,Diya Patel,diya.patel390@gmail.com,+91-9451285631,Lucknow,Male,2023-07-09,VIP
162,161,Deepak Iyer,deepak.iyer45@hotmail.com,+91-9774548037,Kanpur,Other,2023-10-08,Premium
195,194,Priya Reddy,priya.reddy483@rediffmail.com,+91-9672811787,Pune,Other,2023-02-26,Premium
...,...,...,...,...,...,...,...,...
5963,5863,Kritika Desai,kritika.desai465@outlook.com,+91-9882726534,Delhi,Other,2021-01-31,Regular
5969,5868,Riya Gupta,riya.gupta90@gmail,+91-7619521582,Kolkata,Female,2020-10-01,New
5992,5890,Ayaan Bansal,ayaan.bansal666@rediffmail.com,+91-9050904020,Ludhiana,Male,2019-04-11,New
6056,5953,Riya Nair,riya.nair132@hotmail,+91-9545979734,Indore,Female,2024-09-27,Premium
6084,5981,Pari Singh,pari.singh825@rediffmail.com,+91-8305729152,Nashik,Female,2019-10-28,Regular

In [79]:
customers["phone"] = customers["phone"].str.replace("+91-","", regex=False)

In [81]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5693 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5693 non-null   int64
 1   customer_name      5535 non-null   str
 2   email              5693 non-null   str
 3   phone              5693 non-null   str
 4   city               5693 non-null   str
 5   gender             5693 non-null   str
 6   registration_date  5693 non-null   datetime64[us]
 7   customer_segment   5693 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 400.3 KB

In [80]:
customers["phone"].head()
customers["phone"].dtype

In [75]:
customers["phone"].astype(int)

0       7239980629
1       9452970852
2       9244739576
3       8786250248
4       8700894595
           ...
6098    9237530917
6099    9780355175
6100    9612818909
6101    8614416116
6103    8462637022
Name: phone, Length: 5693, dtype: int64

In [65]:

customers["registration_date"] = pd.to_datetime(customers["registration_date"])

In [76]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5693 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5693 non-null   int64
 1   customer_name      5535 non-null   str
 2   email              5693 non-null   str
 3   phone              5693 non-null   str
 4   city               5693 non-null   str
 5   gender             5693 non-null   str
 6   registration_date  5693 non-null   datetime64[us]
 7   customer_segment   5693 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 400.3 KB

In [66]:
customers["registration_date"].astype(int)

0       1555372800000000
1       1655251200000000
2       1659398400000000
3       1643673600000000
4       1580342400000000
              ...
6098    1593129600000000
6099    1625443200000000
6100    1578787200000000
6101    1679184000000000
6103    1658275200000000
Name: registration_date, Length: 5693, dtype: int64

In [67]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5693 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5693 non-null   int64
 1   customer_name      5535 non-null   str
 2   email              5693 non-null   str
 3   phone              5693 non-null   str
 4   city               5693 non-null   str
 5   gender             5693 non-null   str
 6   registration_date  5693 non-null   datetime64[us]
 7   customer_segment   5693 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 400.3 KB

In [42]:
df.shape

(48000, 7)

In [5]:
customers["customer_name"].fillna("Unknown", inplace=True)

C:\Users\kiran\AppData\Local\Temp\ipykernel_5756\561585338.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  customers["customer_name"].fillna("Unknown", inplace=True)

0        Ramesh Verma
1        Deepak Gupta
2       Vihaan Kapoor
3         Priya Singh
4        Sanjay Joshi
            ...
6099        Pari Iyer
6100     Vivaan Joshi
6101     Diya Agarwal
6102      Aarav Gupta
6103         Neha Rao
Name: customer_name, Length: 6104, dtype: str

In [48]:
# remove duplicate values
customers.duplicated().sum()

np.int64(104)

In [49]:
customers.drop_duplicates(inplace=True)

In [50]:
customers.duplicated().sum()

np.int64(0)

In [54]:
# extra space remove
customers["customer_name"] = customers["customer_name"].str.strip()

In [55]:
# check invalid emails
customers["email"].str.contains("@").value_counts()

email
True     5693
False     307
Name: count, dtype: int64

In [60]:
customers[~customers["email"].str.contains("@" , na=False)]

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
8,9,Arjun Iyer,arjun.iyer224outlook.com,9748079890,Bhopal,Male,2024-06-04,Premium
23,24,Sai Desai,sai.desai108yahoo.com,+91-7655181723,Ludhiana,Male,2023-07-28,Regular
43,44,Diya Singh,diya.singh20yahoo.com,8132751855,Patna,Female,2022-09-26,Regular
61,61,Ishaan Nair,ishaan.nair823rediffmail.com,9949436387,Mumbai,Female,2020-11-08,Premium
67,67,Riya Bansal,riya.bansal917hotmail.com,7857154699,Jaipur,Male,2023-02-26,New
...,...,...,...,...,...,...,...,...
6025,5923,Rahul Bhatt,rahul.bhatt918yahoo.com,7123348069,Kolkata,Other,2020-03-30,VIP
6028,5926,Pari Rao,pari.rao179yahoo.com,7381358134,Kolkata,Male,2024-01-13,Regular
6036,5934,Kritika Rao,kritika.rao329rediffmail.com,9052070595,Surat,Other,2023-11-16,New
6074,5971,Riya Agarwal,riya.agarwal259hotmail.com,9764919033,Kanpur,Female,2020-05-24,VIP
6102,5999,Aarav Gupta,aarav.gupta173rediffmail.com,7809015939,Jaipur,Male,2020-08-13,Premium

In [69]:
# remove invalid emils
customers = customers[customers["email"].str.contains("@", na=False)]

In [72]:
customers["email"].str.contains("@").value_counts()

email
True    5693
Name: count, dtype: int64

In [73]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5693 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5693 non-null   int64
 1   customer_name      5535 non-null   str
 2   email              5693 non-null   str
 3   phone              5693 non-null   str
 4   city               5693 non-null   str
 5   gender             5693 non-null   str
 6   registration_date  5693 non-null   datetime64[us]
 7   customer_segment   5693 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 400.3 KB

In [82]:
customers["phone"].str.len().value_counts()

phone
10    5438
7       89
8       85
9       81
Name: count, dtype: int64

In [85]:
customers["phone"] = customers["phone"].str.replace(r"\D","", regex=True)

In [86]:
customers["phone"].str.len().value_counts()

phone
10    5438
7       89
8       85
9       81
Name: count, dtype: int64

In [87]:
customers["phone"] = customers["phone"].astype(str)
customers["phone"] = customers["phone"].str.replace(r"\D", "", regex=True)

In [88]:
customers["phone"].str.len().value_counts()

phone
10    5438
7       89
8       85
9       81
Name: count, dtype: int64

In [91]:
customers[customers["phone"].str.len() !=10]

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
60,60,Ishaan Bhatt,ishaan.bhatt852@rediffmail.com,7208195,Kolkata,Other,2024-03-09,Premium
144,143,Nikhil Chopra,nikhil.chopra166@yahoo.com,91612370,Kolkata,Male,2023-11-20,VIP
237,236,Vihaan Bhatt,vihaan.bhatt71@yahoo.com,9664958,Agra,Male,2024-07-09,Regular
248,247,Meera Bansal,meera.bansal292@gmail.com,790838022,Chennai,Male,2020-04-06,New
328,326,Priya Kapoor,priya.kapoor905@outlook.com,88030612,Bengaluru,Female,2024-09-01,Regular
...,...,...,...,...,...,...,...,...
6026,5924,Amit Sharma,amit.sharma31@hotmail.com,878116582,Indore,Other,2022-12-06,New
6031,5929,Ayaan Agarwal,ayaan.agarwal587@yahoo.com,9546197,Bhopal,Male,2020-12-03,Regular
6050,5948,Shreya Mehta,shreya.mehta728@yahoo.com,8938937,Ahmedabad,Other,2019-10-27,New
6052,5950,Sai Verma,sai.verma41@yahoo.com,738932963,Nashik,Other,2023-05-28,VIP
6082,5979,Amit Joshi,amit.joshi538@yahoo.com,7824895,Agra,Female,2023-05-26,VIP

In [34]:
 customers[customers["phone"].str.len() == 10]

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
0,1,Ramesh Verma,ramesh.verma495@outlook.com,7239980629,Pune,Female,2019-04-16,New
1,2,Deepak Gupta,deepak.gupta505@rediffmail.com,9452970852,Delhi,Male,2022-06-15,Premium
2,3,Vihaan Kapoor,vihaan.kapoor995@outlook.com,9244739576,Kanpur,Female,2022-08-02,New
3,4,Priya Singh,priya.singh209@gmail.com,8786250248,Indore,Male,2022-02-01,New
4,5,Sanjay Joshi,sanjay.joshi872@outlook.com,8700894595,Bengaluru,Other,2020-01-30,New
...,...,...,...,...,...,...,...,...
6099,5996,Pari Iyer,pari.iyer597@rediffmail.com,9780355175,Bengaluru,Female,2021-07-05,VIP
6100,5997,Vivaan Joshi,vivaan.joshi57@yahoo.com,9612818909,Jaipur,Male,2020-01-12,Premium
6101,5998,Diya Agarwal,diya.agarwal527@yahoo.com,8614416116,Ludhiana,Male,2023-03-19,VIP
6102,5999,Aarav Gupta,aarav.gupta173rediffmail.com,7809015939,Jaipur,Male,2020-08-13,Premium
6103,6000,Neha Rao,neha.rao502@yahoo.com,8462637022,Kolkata,Male,2022-07-20,New

In [93]:
customers["phone"].str.len().value_counts()

phone
10    5438
Name: count, dtype: int64

In [95]:
customers.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'city', 'gender',
       'registration_date', 'customer_segment'],
      dtype='str')

In [96]:
customers["customer_segment"].unique()

<StringArray>
['New', 'Premium', 'VIP', 'Regular']
Length: 4, dtype: str

In [97]:
customers["customer_segment"].value_counts()

customer_segment
New        1386
Regular    1384
VIP        1372
Premium    1296
Name: count, dtype: int64

In [98]:
customers["customer_segment"].isnull().sum()

np.int64(0)

In [99]:
customers.info()

<class 'pandas.DataFrame'>
Index: 5438 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5438 non-null   int64
 1   customer_name      5286 non-null   str
 2   email              5438 non-null   str
 3   phone              5438 non-null   str
 4   city               5438 non-null   str
 5   gender             5438 non-null   str
 6   registration_date  5438 non-null   datetime64[us]
 7   customer_segment   5438 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 382.4 KB

In [100]:
df.shape

(48000, 7)

In [98]:
customers.describe(include="all")

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
count,6104.000000,5939,6104,6104,6104,6104,6104,6104
unique,NaN,798,5994,6000,97,3,2043,4
top,NaN,Aarav Gupta,pari.reddy94@outlook,7425587239,Jaipur,Male,2020-01-20,Regular
freq,NaN,17,2,2,333,2089,10,1567
mean,3003.345839,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1733.072878,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1500.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,3003.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4504.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,6000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
customers["customer_name"].isnull().sum()

np.int64(165)

In [100]:
customers["customer_name"] = customers["customer_name"].fillna("unknown")

In [101]:
customers["customer_name"].isnull().sum()

np.int64(0)

In [102]:
customers["city"] = customers["city"].str.strip().str.title()

In [103]:
customers["city"].head()

0         Pune
1        Delhi
2       Kanpur
3       Indore
4    Bengaluru
Name: city, dtype: str

In [104]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
city                 0
gender               0
registration_date    0
customer_segment     0
dtype: int64

In [105]:
customers.shape

(6104, 8)

In [106]:
customers["customer_id"].nunique()

6000

In [107]:
customers.duplicated().sum()

np.int64(104)

In [108]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 6104 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        6104 non-null   int64
 1   customer_name      6104 non-null   str
 2   email              6104 non-null   str
 3   phone              6104 non-null   str
 4   city               6104 non-null   str
 5   gender             6104 non-null   str
 6   registration_date  6104 non-null   str
 7   customer_segment   6104 non-null   str
dtypes: int64(1), str(7)
memory usage: 381.6 KB

In [109]:
customers.describe(include="all")

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
count,6104.000000,6104,6104,6104,6104,6104,6104,6104
unique,NaN,799,5994,6000,32,3,2043,4
top,NaN,unknown,pari.reddy94@outlook,7425587239,Jaipur,Male,2020-01-20,Regular
freq,NaN,165,2,2,340,2089,10,1567
mean,3003.345839,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1733.072878,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1500.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,3003.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4504.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,6000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
customers["gender"].value_counts()

gender
Male      2089
Female    2013
Other     2002
Name: count, dtype: int64

In [111]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
city                 0
gender               0
registration_date    0
customer_segment     0
dtype: int64

In [113]:
customers[customers["customer_name"].isnull()]

Empty DataFrame
Columns: [customer_id, customer_name, email, phone, city, gender, registration_date, customer_segment]
Index: []

In [114]:
customers["customer_name"] = customers["customer_name"].fillna("Unknown")

In [115]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
city                 0
gender               0
registration_date    0
customer_segment     0
dtype: int64

In [116]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 6104 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        6104 non-null   int64
 1   customer_name      6104 non-null   str
 2   email              6104 non-null   str
 3   phone              6104 non-null   str
 4   city               6104 non-null   str
 5   gender             6104 non-null   str
 6   registration_date  6104 non-null   str
 7   customer_segment   6104 non-null   str
dtypes: int64(1), str(7)
memory usage: 381.6 KB

In [117]:
customers["customer_id"].nunique()

6000

In [118]:
customers["customer_id"].duplicated().sum()

np.int64(104)

In [119]:
customers[customers["customer_id"].duplicated(keep=False)].sort_values("customer_id")

,customer_id,customer_name,email,phone,city,gender,registration_date,customer_segment
44,45,Pari Reddy,pari.reddy94@outlook,7425587239,Ahmedabad,Other,2023-09-28,New
45,45,Pari Reddy,pari.reddy94@outlook,7425587239,Ahmedabad,Other,2023-09-28,New
134,134,Suresh Sharma,suresh.sharma905@gmail.com,8816320963,Patna,Female,2023-06-07,Regular
135,134,Suresh Sharma,suresh.sharma905@gmail.com,8816320963,Patna,Female,2023-06-07,Regular
256,255,Anjali Reddy,anjali.reddy542@hotmail.com,7121860478,Mumbai,Other,2022-02-11,Regular
...,...,...,...,...,...,...,...,...
5965,5864,Pari Bansal,pari.bansal419@yahoo.com,9284329862,Nagpur,Male,2020-08-30,New
5972,5871,Saanvi Kapoor,saanvi.kapoor818@gmail.com,8607177474,Agra,Other,2019-01-08,Regular
5973,5871,Saanvi Kapoor,saanvi.kapoor818@gmail.com,8607177474,Agra,Other,2019-01-08,Regular
6052,5950,Sai Verma,sai.verma41@yahoo.com,738932963,Nashik,Other,2023-05-28,VIP
6053,5950,Sai Verma,sai.verma41@yahoo.com,738932963,Nashik,Other,2023-05-28,VIP

In [120]:
customers = customers.drop_duplicates(subset="customer_id", keep="first")

In [121]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [122]:
customers.shape

(6000, 8)

In [123]:
customers["customer_id"].nunique()

6000

In [124]:
print("Total Rows:", len(customers))
print("Unique Customer IDs:", customers["customer_id"].nunique())
print("Duplicate Customer IDs:", customers["customer_id"].duplicated().sum())
print("Missing Customer IDs:", customers["customer_id"].isna().sum())

Total Rows: 6000
Unique Customer IDs: 6000
Duplicate Customer IDs: 0
Missing Customer IDs: 0

In [125]:
customers.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'city', 'gender',
       'registration_date', 'customer_segment'],
      dtype='str')

In [126]:
customers = customers.drop_duplicates(subset=["customer_id"])

In [127]:
customers.shape

(6000, 8)

In [128]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
city                 0
gender               0
registration_date    0
customer_segment     0
dtype: int64

In [129]:
customers["customer_name"] = customers["customer_name"].fillna("Unknown")

In [130]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
city                 0
gender               0
registration_date    0
customer_segment     0
dtype: int64

In [131]:
customers[customers["phone"].astype(str).str.len() != 10][["customer_id", "phone"]]

      customer_id           phone
23             24  +91-7655181723
50             50  +91-9901714208
60             60         7208195
144           143        91612370
151           150  +91-9451285631
...           ...             ...
6050         5948         8938937
6052         5950       738932963
6056         5953  +91-9545979734
6082         5979         7824895
6084         5981  +91-8305729152

[511 rows x 2 columns]

In [133]:
# Phone number ko string mein convert karo
customers["phone"] = customers["phone"].astype(str)

# +91, -, spaces, brackets etc. remove karke sirf digits rakho
customers["phone"] = customers["phone"].str.replace(r"\D", "", regex=True)

# Agar number 91 se start ho aur total 12 digits ho,
# to starting ke 91 ko remove karo
customers.loc[
    customers["phone"].str.len() == 12,
    "phone"
] = customers.loc[
    customers["phone"].str.len() == 12,
    "phone"
].str[2:]

In [134]:
customers[customers["phone"].str.len() != 10][["customer_id", "phone"]]

      customer_id      phone
60             60    7208195
144           143   91612370
184           183  826822896
237           236    9664958
248           247  790838022
...           ...        ...
6026         5924  878116582
6031         5929    9546197
6050         5948    8938937
6052         5950  738932963
6082         5979    7824895

[269 rows x 2 columns]

In [135]:
import numpy as np

customers.loc[
    customers["phone"].str.len() != 10,
    "phone"
] = np.nan

In [136]:
customers["phone"].isnull().sum()

np.int64(269)

In [137]:
customers[["customer_name", "gender"]].head(20)

    customer_name  gender
0    Ramesh Verma  Female
1    Deepak Gupta    Male
2   Vihaan Kapoor  Female
3     Priya Singh    Male
4    Sanjay Joshi   Other
5     Ayaan Kumar   Other
6       Isha Nair    Male
7         unknown   Other
8      Arjun Iyer    Male
9   Karan Agarwal   Other
10  Sanjay Chopra  Female
11   Ayaan Chopra   Other
12  Deepak Sharma    Male
13   Rahul Pillai    Male
14     Amit Reddy    Male
15  Ramesh Pillai    Male
16    Myra Pillai    Male
17     Aditya Rao   Other
18    Sneha Reddy    Male
19    Aarav Desai    Male

In [138]:
# First name extract karo
first_name = customers["customer_name"].astype(str).str.strip().str.split().str[0]

# Male names
male_names = [
    "Aarav", "Ayaan", "Aditya", "Amit", "Arjun",
    "Deepak", "Ishaan", "Karan", "Krishna", "Manish",
    "Nikhil", "Rahul", "Ramesh", "Reyansh", "Rohan",
    "Sai", "Sanjay", "Suresh", "Vihaan", "Vivaan"
]

# Female names
female_names = [
    "Aadhya", "Ananya", "Anika", "Anjali", "Divya",
    "Diya", "Isha", "Kavya", "Kritika", "Meera",
    "Myra", "Neha", "Pari", "Pooja", "Priya",
    "Riya", "Saanvi", "Shreya", "Sneha", "Sunita"
]

# Poore gender column ko correct karo
customers.loc[first_name.isin(male_names), "gender"] = "Male"
customers.loc[first_name.isin(female_names), "gender"] = "Female"

# Unknown customer ko Other rakho
customers.loc[first_name == "Unknown", "gender"] = "Other"

print("Gender correction completed!")

Gender correction completed!

In [139]:
customers["gender"].value_counts()

gender
Female    2988
Male      2958
Other       54
Name: count, dtype: int64

In [140]:
customers.groupby(
    customers["customer_name"].str.split().str[0]
)["gender"].value_counts()

customer_name  gender
Aadhya         Female    130
Aarav          Male      171
Aditya         Male      134
Amit           Male      144
Ananya         Female    144
Anika          Female    151
Anjali         Female    141
Arjun          Male      139
Ayaan          Male      155
Deepak         Male      149
Divya          Female    163
Diya           Female    155
Isha           Female    133
Ishaan         Male      146
Karan          Male      127
Kavya          Female    145
Krishna        Male      135
Kritika        Female    151
Manish         Male      146
Meera          Female    163
Myra           Female    138
Neha           Female    146
Nikhil         Male      128
Pari           Female    172
Pooja          Female    145
Priya          Female    143
Rahul          Male      145
Ramesh         Male      155
Reyansh        Male      133
Riya           Female    139
Rohan          Male      134
Saanvi         Female    119
Sai            Male      148
Sanjay         Male      131
Shreya         Female    152
Sneha          Female    146
Sunita         Female    160
Suresh         Male      178
Vihaan         Male      135
Vivaan         Male      166
unknown        Male       59
               Other      54
               Female     52
Name: count, dtype: int64

In [141]:
customers.describe()

       customer_id
count  6000.000000
mean   3000.500000
std    1732.195139
min       1.000000
25%    1500.750000
50%    3000.500000
75%    4500.250000
max    6000.000000

In [142]:
customers.isnull().sum()

customer_id            0
customer_name          0
email                  0
phone                269
city                   0
gender                 0
registration_date      0
customer_segment       0
dtype: int64

In [143]:
customers[customers["phone"].isnull()][
    ["customer_id", "customer_name", "phone"]
]

      customer_id  customer_name phone
60             60   Ishaan Bhatt   NaN
144           143  Nikhil Chopra   NaN
184           183    Aarav Mehta   NaN
237           236   Vihaan Bhatt   NaN
248           247   Meera Bansal   NaN
...           ...            ...   ...
6026         5924    Amit Sharma   NaN
6031         5929  Ayaan Agarwal   NaN
6050         5948   Shreya Mehta   NaN
6052         5950      Sai Verma   NaN
6082         5979     Amit Joshi   NaN

[269 rows x 3 columns]

In [144]:
customers["email"].isnull().sum()

np.int64(0)

In [145]:
customers["email"].head(20)

0        ramesh.verma495@outlook.com
1     deepak.gupta505@rediffmail.com
2       vihaan.kapoor995@outlook.com
3           priya.singh209@gmail.com
4        sanjay.joshi872@outlook.com
5           ayaan.kumar661@yahoo.com
6             isha.nair347@yahoo.com
7       isha.verma900@rediffmail.com
8          arjun.iyer224@outlook.com
9       karan.agarwal583@hotmail.com
10      sanjay.chopra978@hotmail.com
11         ayaan.chopra290@yahoo.com
12      deepak.sharma271@hotmail.com
13     rahul.pillai85@rediffmail.com
14      amit.reddy138@rediffmail.com
15          ramesh.pillai8@yahoo.com
16     myra.pillai621@rediffmail.com
17           aditya.rao412@gmail.com
18        sneha.reddy525@hotmail.com
19           aarav.desai25@yahoo.com
Name: email, dtype: str

In [146]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [147]:
print("Missing Emails:", customers["email"].isnull().sum())
print("Duplicate Customer IDs:", customers["customer_id"].duplicated().sum())

Missing Emails: 0
Duplicate Customer IDs: 0

In [148]:
customers.info()

<class 'pandas.DataFrame'>
Index: 6000 entries, 0 to 6103
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        6000 non-null   int64
 1   customer_name      6000 non-null   str
 2   email              6000 non-null   str
 3   phone              5731 non-null   str
 4   city               6000 non-null   str
 5   gender             6000 non-null   str
 6   registration_date  6000 non-null   str
 7   customer_segment   6000 non-null   str
dtypes: int64(1), str(7)
memory usage: 421.9 KB

In [149]:
customers.isnull().sum()

customer_id            0
customer_name          0
email                  0
phone                269
city                   0
gender                 0
registration_date      0
customer_segment       0
dtype: int64

In [150]:
customers["phone"] = customers["phone"].fillna("Not Available")

In [151]:
customers["phone"].isnull().sum()

np.int64(0)

In [152]:
import re

def fix_email(email):
    if pd.isna(email):
        return email
    
    email = str(email).strip()

    # Agar @ already hai, email ko change mat karo
    if "@" in email:
        return email

    # Missing @ ko domain se pehle add karo
    domains = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "rediffmail.com"]

    for domain in domains:
        if email.endswith(domain):
            return email.replace(domain, "@" + domain)

    return email

customers["email"] = customers["email"].apply(fix_email)

In [90]:
customers["email"].head(20)

0        ramesh.verma495@outlook.com
1     deepak.gupta505@rediffmail.com
2       vihaan.kapoor995@outlook.com
3           priya.singh209@gmail.com
4        sanjay.joshi872@outlook.com
5           ayaan.kumar661@yahoo.com
6             isha.nair347@yahoo.com
7       isha.verma900@rediffmail.com
8          arjun.iyer224@outlook.com
9       karan.agarwal583@hotmail.com
10      sanjay.chopra978@hotmail.com
11         ayaan.chopra290@yahoo.com
12      deepak.sharma271@hotmail.com
13     rahul.pillai85@rediffmail.com
14      amit.reddy138@rediffmail.com
15          ramesh.pillai8@yahoo.com
16     myra.pillai621@rediffmail.com
17           aditya.rao412@gmail.com
18        sneha.reddy525@hotmail.com
19           aarav.desai25@yahoo.com
Name: email, dtype: str

In [153]:
customers[~customers["email"].str.contains("@", na=False)][["email"]]

Empty DataFrame
Columns: [email]
Index: []

In [154]:
customers.to_csv("customers_cleaned.csv", index=False)

In [119]:
# Categories csv file has alread cleaned
categories.describe(include="all")

        category_id category_name
count     15.000000            15
unique          NaN            15
top             NaN     Groceries
freq            NaN             1
mean       8.000000           NaN
std        4.472136           NaN
min        1.000000           NaN
25%        4.500000           NaN
50%        8.000000           NaN
75%       11.500000           NaN
max       15.000000           NaN

In [120]:
categories.head()

   category_id   category_name
0            1       Groceries
1            2     Electronics
2            3         Apparel
3            4        Footwear
4            5  Home & Kitchen

In [121]:
categories.isnull().sum()

category_id      0
category_name    0
dtype: int64

In [100]:
categories.to_csv("categories_cleaned.csv", index=False)

In [122]:
products.head()

,product_id,product_name,category_id,supplier_id,cost_price_inr,unit_price_inr
0,1,Ultra Fruit Juice 1L,14,17,2398.34,4155.72
1,2,Royal Kurta Set,3,31,3140.68,4148.41
2,3,Deluxe Wheat Flour 10kg,1,26,2435.22,4282.73
3,4,Classic Kurta Set,3,34,747.60,1276.82
4,5,Smart Notebook Pack,9,35,9454.05,13294.92

In [123]:
products.isnull().sum()

product_id        0
product_name      0
category_id       0
supplier_id       0
cost_price_inr    7
unit_price_inr    0
dtype: int64

In [124]:
products.describe(include="all")

,product_id,product_name,category_id,supplier_id,cost_price_inr,unit_price_inr
count,360.000000,360,360.000000,360.000000,353.000000,360.000000
unique,NaN,262,NaN,NaN,NaN,NaN
top,NaN,Smart Bluetooth Speaker,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,NaN,NaN,NaN
mean,180.500000,NaN,7.775000,43.166667,6422.913031,10048.359000
std,104.067286,NaN,4.459279,135.421801,5177.949128,6597.169548
min,1.000000,NaN,1.000000,1.000000,-14559.410000,152.440000
25%,90.750000,NaN,4.000000,13.000000,2718.880000,4449.247500
50%,180.500000,NaN,7.000000,25.000000,6145.750000,9302.105000
75%,270.250000,NaN,12.000000,37.000000,10649.930000,15242.717500
max,360.000000,NaN,15.000000,999.000000,14999.090000,24984.810000

In [144]:
products.rename(columns = {'cost_price_inr':'cost_price'},inplace=True)

In [146]:
# Outliers
products['cost_price'] = products['cost_price'].fillna(products['cost_price'].median())

0       2398.34
1       3140.68
2       2435.22
3        747.60
4       9454.05
         ...
355     1531.59
356     6252.09
357    10645.08
358     5468.56
359     6727.05
Name: cost_price, Length: 360, dtype: float64

In [148]:
products.isnull().sum()

product_id      0
product_name    0
category_id     0
supplier_id     0
cost_price      0
unit_price      0
dtype: int64

In [151]:
products.duplicated().sum()

np.int64(0)

In [152]:
products['product_id'].duplicated().sum()

np.int64(0)

In [153]:
products.dtypes

product_id        int64
product_name        str
category_id       int64
supplier_id       int64
cost_price      float64
unit_price      float64
dtype: object

In [18]:
products.shape

(360, 6)

In [19]:
products.isnull().sum()

product_id        0
product_name      0
category_id       0
supplier_id       0
cost_price_inr    7
unit_price_inr    0
dtype: int64

In [65]:
(products["cost_price_inr"]<0).sum()

np.int64(13)

In [66]:
products["cost_price_inr"] = products["cost_price_inr"].abs()

In [67]:
(products["cost_price_inr"]<0).sum()

np.int64(0)

In [72]:
products.isnull().sum()

product_id        0
product_name      0
category_id       0
supplier_id       0
cost_price_inr    7
unit_price_inr    0
dtype: int64

In [73]:
products["cost_price_inr"].median()

np.float64(6686.56)

In [74]:
products["cost_price_inr"] = products["cost_price_inr"].fillna(
    products["cost_price_inr"].median()
)

In [75]:
products.isnull().sum()

product_id        0
product_name      0
category_id       0
supplier_id       0
cost_price_inr    0
unit_price_inr    0
dtype: int64

In [76]:
products["product_id"].duplicated().sum()

np.int64(0)

In [78]:
products.to_csv("dim2_products_cleaned.csv", index=False)

In [7]:
products['product_id'].duplicated().sum()

np.int64(0)

In [150]:
stores.isnull().sum()

store_id        0
store_name      0
city            0
state           0
store_type      0
opening_date    0
manager_name    0
dtype: int64

In [34]:
# Clean stores CSV file
stores.head()

,store_id,store_name,city,state,store_type,opening_date,manager_name
0,1,Lucknow Mall Outlet Store 1,Lucknow,Uttar Pradesh,Mall Outlet,2019-06-06,Vihaan Gupta
1,2,Hyderabad Standalone Store 2,Hyderabad,Telangana,Standalone,2021-07-15,Vihaan Joshi
2,3,Bengaluru Franchise Store 3,Bengaluru,Karnataka,Franchise,2019-09-09,Arjun Mehta
3,4,Indore Flagship Store 4,Indore,Madhya Pradesh,Flagship,2021-05-05,Ayaan Mehta
4,5,Agra Flagship Store 5,Agra,Uttar Pradesh,Flagship,2021-06-21,Meera Chopra

In [35]:
stores.isnull().sum()

store_id        0
store_name      0
city            0
state           0
store_type      0
opening_date    0
manager_name    0
dtype: int64

In [36]:
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      35 non-null     int64
 1   store_name    35 non-null     str
 2   city          35 non-null     str
 3   state         35 non-null     str
 4   store_type    35 non-null     str
 5   opening_date  35 non-null     str
 6   manager_name  35 non-null     str
dtypes: int64(1), str(6)
memory usage: 2.0 KB

In [37]:
stores["opening_date"] = pd.to_datetime(stores["opening_date"])

In [38]:
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      35 non-null     int64
 1   store_name    35 non-null     str
 2   city          35 non-null     str
 3   state         35 non-null     str
 4   store_type    35 non-null     str
 5   opening_date  35 non-null     datetime64[us]
 6   manager_name  35 non-null     str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 2.0 KB

In [39]:
stores.duplicated().sum()

np.int64(0)

In [40]:
# Blank values
(stores == "").sum()

store_id        0
store_name      0
city            0
state           0
store_type      0
opening_date    0
manager_name    0
dtype: int64

In [41]:
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      35 non-null     int64
 1   store_name    35 non-null     str
 2   city          35 non-null     str
 3   state         35 non-null     str
 4   store_type    35 non-null     str
 5   opening_date  35 non-null     datetime64[us]
 6   manager_name  35 non-null     str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 2.0 KB

In [42]:
print(stores["city"].unique())
print(stores["state"].unique())
print(stores["store_type"].unique())

<StringArray>
[  'Lucknow', 'Hyderabad', 'Bengaluru',    'Indore',      'Agra',      'Pune',
  'Ludhiana',   'Chennai',    'Kanpur',     'Surat', 'Ahmedabad',    'Bhopal',
     'Patna',    'Nagpur',    'Mumbai',     'Delhi',   'Kolkata']
Length: 17, dtype: str
<StringArray>
[ 'Uttar Pradesh',      'Telangana',      'Karnataka', 'Madhya Pradesh',
    'Maharashtra',         'Punjab',     'Tamil Nadu',        'Gujarat',
          'Bihar',          'Delhi',    'West Bengal']
Length: 11, dtype: str
<StringArray>
['Mall Outlet', 'Standalone', 'Franchise', 'Flagship', 'Kiosk']
Length: 5, dtype: str

In [43]:
stores.columns

Index(['store_id', 'store_name', 'city', 'state', 'store_type', 'opening_date',
       'manager_name'],
      dtype='str')

In [32]:
stores["store_id"].nunique()

35

In [44]:
stores.describe()

        store_id         opening_date
count  35.000000                   35
mean   18.000000  2019-09-21 14:24:00
min     1.000000  2015-04-05 00:00:00
25%     9.500000  2018-09-01 12:00:00
50%    18.000000  2020-03-23 00:00:00
75%    26.500000  2021-05-07 12:00:00
max    35.000000  2022-11-13 00:00:00
std    10.246951                  NaN

In [45]:
#column names ke extra spaces remove 
stores.columns = stores.columns.str.strip()

In [46]:
# this will remove any extra spaces at the start and end of a value.
text_columns = ["store_name", "city", "state", "store_type", "manager_name"]

for col in text_columns:
    stores[col] = stores[col].str.strip()

In [47]:
stores.isnull().sum()

store_id        0
store_name      0
city            0
state           0
store_type      0
opening_date    0
manager_name    0
dtype: int64

In [48]:
stores.duplicated().sum()

np.int64(0)

In [49]:
stores["store_id"].duplicated().sum()

np.int64(0)

In [50]:
stores = stores[
    ["store_id", "store_name", "store_type", "city",
     "state", "opening_date", "manager_name"]
]

In [51]:
stores["opening_date"] = pd.to_datetime(
    stores["opening_date"],
    dayfirst=True,
    errors="coerce"
)

In [52]:
stores.head()

,store_id,store_name,store_type,city,state,opening_date,manager_name
0,1,Lucknow Mall Outlet Store 1,Mall Outlet,Lucknow,Uttar Pradesh,2019-06-06,Vihaan Gupta
1,2,Hyderabad Standalone Store 2,Standalone,Hyderabad,Telangana,2021-07-15,Vihaan Joshi
2,3,Bengaluru Franchise Store 3,Franchise,Bengaluru,Karnataka,2019-09-09,Arjun Mehta
3,4,Indore Flagship Store 4,Flagship,Indore,Madhya Pradesh,2021-05-05,Ayaan Mehta
4,5,Agra Flagship Store 5,Flagship,Agra,Uttar Pradesh,2021-06-21,Meera Chopra

In [53]:
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      35 non-null     int64
 1   store_name    35 non-null     str
 2   store_type    35 non-null     str
 3   city          35 non-null     str
 4   state         35 non-null     str
 5   opening_date  35 non-null     datetime64[us]
 6   manager_name  35 non-null     str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 2.0 KB

In [55]:
stores.to_csv("dim_stores_cleaned.csv", index=False)

In [171]:
# clean data supplier csv files
suppliers.isnull().sum()

supplier_id      0
supplier_name    0
city             0
contact_name     0
contact_email    0
contact_phone    1
rating           0
dtype: int64

In [56]:
suppliers.info()

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   supplier_id    45 non-null     int64
 1   supplier_name  45 non-null     str
 2   city           45 non-null     str
 3   contact_name   45 non-null     str
 4   contact_email  45 non-null     str
 5   contact_phone  44 non-null     str
 6   rating         45 non-null     float64
dtypes: float64(1), int64(1), str(5)
memory usage: 2.6 KB

In [57]:
suppliers.rename(columns = {'phone': 'contact_phone'})

,supplier_id,supplier_name,city,contact_name,contact_email,contact_phone,rating
0,1,Prime Traders Industries,Surat,Sai Singh,sai.singh376@hotmail.com,8388853933,1.9
1,2,Sunrise Traders Pvt Ltd,Jaipur,Priya Singh,priya.singh710@yahoo.com,8755131373,3.5
2,3,Bharat Mart & Co,Bengaluru,Ayaan Chopra,ayaan.chopra490@yahoo.com,9516761222,4.6
3,4,Om Mart & Co,Ahmedabad,Shreya Desai,shreya.desai22yahoo.com,7826330434,3.3
4,5,Silver Enterprises Pvt Ltd,Kanpur,Ramesh Kapoor,ramesh.kapoor431@hotmail.com,9282880729,1.6
5,6,Trident Distributors Industries,Delhi,Rohan Joshi,rohan.joshi569@hotmail.com,780334018,2.8
6,7,Prime Industries & Co,Bhopal,Pooja Desai,pooja.desai520@rediffmail.com,+91-8483726167,2.0
7,8,National Distributors LLP,Kanpur,Ishaan Singh,ishaan.singh991@yahoo.com,8672326865,2.3
8,9,Bharat Supplies Industries,Bhopal,Suresh Sharma,suresh.sharma340@rediffmail.com,9811311440,1.5
9,10,National Impex LLP,Ludhiana,Pooja Kapoor,pooja.kapoor718@rediffmail.com,7026140141,1.3
10,11,Golden Traders & Co,Ludhiana,Deepak Singh,deepak.singh133hotmail.com,9124023448,3.0
11,12,Sunrise Traders & Co,Delhi,Aarav Sharma,aarav.sharma565@hotmail.com,8737167868,4.9
12,13,Om Impex & Co,Delhi,Krishna Sharma,krishna.sharma641@gmail.com,7620168493,2.8
13,14,Golden Traders & Co,Kanpur,Karan Desai,karan.desai251outlook.com,7352056174,2.0
14,15,Shree Wholesale Pvt Ltd,Ahmedabad,Sanjay Kapoor,sanjay.kapoor404gmail.com,9319829657,3.5
15,16,Prime Impex Industries,Ahmedabad,Sneha Joshi,sneha.joshi855@hotmail.com,8931002516,3.5
16,17,Royal Mart & Co,Mumbai,Ramesh Gupta,ramesh.gupta920@hotmail.com,8174143337,1.3
17,18,National Traders Industries,Kolkata,Arjun Bhatt,arjun.bhatt340@yahoo.com,7992070741,3.0
18,19,National Mart Group,Bhopal,Ayaan Desai,ayaan.desai320@yahoo.com,+91-9047187463,1.4
19,20,National Supplies LLP,Nashik,Pooja Singh,pooja.singh721@gmail.com,7760207764,2.4
20,21,Sunrise Traders & Co,Lucknow,Sanjay Iyer,sanjay.iyer731yahoo.com,8451669156,2.1
21,22,National Enterprises LLP,Jaipur,Manish Joshi,manish.joshi195@outlook.com,7068831067,3.6
22,23,Bharat Enterprises LLP,Patna,Deepak Agarwal,deepak.agarwal305@outlook.com,9634786122,4.6
23,24,Royal Mart & Co,Bhopal,Manish Nair,manish.nair198@hotmail.com,9581535493,2.7
24,25,Prime Industries Group,Jaipur,Karan Verma,karan.verma285@rediffmail.com,7288314366,4.8
25,26,Bharat Enterprises Pvt Ltd,Indore,Priya Kapoor,priya.kapoor1@rediffmail,7773132281,4.4
26,27,Shree Traders Pvt Ltd,Ahmedabad,Anika Kapoor,anika.kapoor661@gmail.com,9486111489,1.9
27,28,Bharat Wholesale Group,Jaipur,Rohan Mehta,rohan.mehta539@rediffmail.com,8064003761,2.7
28,29,Golden Traders & Co,Indore,Rahul Chopra,rahul.chopra7@yahoo.com,8137343373,2.2
29,30,Golden Enterprises LLP,Patna,Deepak Verma,deepak.verma150@hotmail.com,8309260026,4.5
30,31,Shree Enterprises & Co,Kolkata,Diya Joshi,diya.joshi33@rediffmail.com,8557210141,4.5
31,32,Royal Impex & Co,Surat,Manish Gupta,manish.gupta723@gmail.com,7873557063,1.2
32,33,Shree Traders & Co,Kolkata,Arjun Bhatt,arjun.bhatt372@outlook.com,9045440910,3.9
33,34,Silver Wholesale Group,Patna,Krishna Pillai,krishna.pillai9@yahoo.com,7293557591,4.0
34,35,Shree Traders Group,Ludhiana,Divya Agarwal,divya.agarwal437@yahoo.com,9491316772,2.8
35,36,Royal Distributors & Co,Surat,Riya Kapoor,riya.kapoor382@outlook.com,9373233249,2.6
36,37,Prime Industries Pvt Ltd,Bhopal,Aditya Iyer,aditya.iyer487@gmail.com,7750431039,1.3
37,38,Om Mart Industries,Jaipur,Aarav Iyer,aarav.iyer727@hotmail.com,NaN,7.3
38,39,Sunrise Enterprises Industries,Surat,Arjun Patel,arjun.patel815@gmail.com,8161682812,2.6
39,40,National Impex Pvt Ltd,Surat,Kritika Bansal,kritika.bansal427rediffmail.com,9366306261,4.5
40,41,Om Enterprises Pvt Ltd,Delhi,Shreya Nair,shreya.nair92@rediffmail.com,9822542821,4.0
41,42,Royal Wholesale LLP,Delhi,Priya Agarwal,priya.agarwal623@gmail.com,9192396937,1.2
42,43,Om Impex & Co,Hyderabad,Ishaan Mehta,ishaan.mehta43@yahoo.com,7516978464,2.6
43,44,Prime Mart LLP,Mumbai,Aarav Bhatt,aarav.bhatt477@rediffmail.com,8727611256,2.8
44,45,Bharat Traders LLP,Bengaluru,Rohan Joshi,rohan.joshi56@gmail.com,9201913274,3.9

In [58]:
suppliers["contact_phone"] =suppliers["contact_phone"].astype(str)
suppliers["contact_phone"] =suppliers["contact_phone"].str.replace("+91-", "", regex=False)

In [59]:
suppliers[suppliers["contact_phone"].str.len() !=10]

,supplier_id,supplier_name,city,contact_name,contact_email,contact_phone,rating
5,6,Trident Distributors Industries,Delhi,Rohan Joshi,rohan.joshi569@hotmail.com,780334018,2.8
37,38,Om Mart Industries,Jaipur,Aarav Iyer,aarav.iyer727@hotmail.com,NaN,7.3

In [60]:
import numpy as np
suppliers.loc[suppliers["contact_phone"].str.len() != 10, "contact_phone"] = np.nan

In [61]:
suppliers["contact_phone"].isnull().sum()

np.int64(2)

In [62]:
suppliers = suppliers.dropna(subset=["contact_phone"])

In [63]:
suppliers["contact_phone"].isnull().sum()

np.int64(0)

In [64]:
suppliers.describe()

       supplier_id     rating
count    43.000000  43.000000
mean     23.046512   2.911628
std      12.979753   1.140010
min       1.000000   1.200000
25%      12.500000   2.000000
50%      23.000000   2.800000
75%      33.500000   3.900000
max      45.000000   4.900000

In [65]:
suppliers[suppliers["contact_email"].str.contains("@", na=False) == False][["contact_email"]]

                      contact_email
3           shreya.desai22yahoo.com
10       deepak.singh133hotmail.com
13        karan.desai251outlook.com
14        sanjay.kapoor404gmail.com
20          sanjay.iyer731yahoo.com
39  kritika.bansal427rediffmail.com

In [75]:
domains = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "rediffmail.com"]

# Pehle saare @ hatao
suppliers["contact_email"] = suppliers["contact_email"].str.replace("@", "", regex=False)

# Domain se just pehle @ add karo
for domain in domains:
    suppliers["contact_email"] = suppliers["contact_email"].str.replace(
        domain, "@" + domain, regex=False
    )

In [76]:
suppliers[suppliers["contact_email"].str.contains("@", na=False) == False][["contact_email"]]

              contact_email
25  priya.kapoor1rediffmail

In [77]:
suppliers["contact_email"].head(20)

0            sai.singh376@hotmail.com
1            priya.singh710@yahoo.com
2           ayaan.chopra490@yahoo.com
3            shreya.desai22@yahoo.com
4        ramesh.kapoor431@hotmail.com
6       pooja.desai520@rediffmail.com
7           ishaan.singh991@yahoo.com
8     suresh.sharma340@rediffmail.com
9      pooja.kapoor718@rediffmail.com
10        deepak.singh133@hotmail.com
11        aarav.sharma565@hotmail.com
12        krishna.sharma641@gmail.com
13         karan.desai251@outlook.com
14         sanjay.kapoor404@gmail.com
15         sneha.joshi855@hotmail.com
16        ramesh.gupta920@hotmail.com
17           arjun.bhatt340@yahoo.com
18           ayaan.desai320@yahoo.com
19           pooja.singh721@gmail.com
20           sanjay.iyer731@yahoo.com
Name: contact_email, dtype: str

In [78]:
import re

suppliers["contact_name"] = suppliers["contact_name"].apply(
    lambda x: re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', str(x))
)

In [79]:
suppliers["contact_name"].head(20)

0          Sai Singh
1        Priya Singh
2       Ayaan Chopra
3       Shreya Desai
4      Ramesh Kapoor
6        Pooja Desai
7       Ishaan Singh
8      Suresh Sharma
9       Pooja Kapoor
10      Deepak Singh
11      Aarav Sharma
12    Krishna Sharma
13       Karan Desai
14     Sanjay Kapoor
15       Sneha Joshi
16      Ramesh Gupta
17       Arjun Bhatt
18       Ayaan Desai
19       Pooja Singh
20       Sanjay Iyer
Name: contact_name, dtype: str

In [82]:
import re

# Pehle existing @ ko remove karo, taaki @@ ki problem na ho
suppliers["contact_email"] = suppliers["contact_email"].astype(str).str.replace("@", "", regex=False)

# Email domains ko automatically correct karo
domains = ["gmail", "yahoo", "outlook", "hotmail", "rediffmail"]

for domain in domains:
    suppliers["contact_email"] = suppliers["contact_email"].str.replace(
        rf"{domain}(\.com)?$",
        "@" + domain + ".com",
        regex=True
    )

In [84]:
suppliers["contact_email"].head(20)

0            sai.singh376@hotmail.com
1            priya.singh710@yahoo.com
2           ayaan.chopra490@yahoo.com
3            shreya.desai22@yahoo.com
4        ramesh.kapoor431@hotmail.com
6       pooja.desai520@rediffmail.com
7           ishaan.singh991@yahoo.com
8     suresh.sharma340@rediffmail.com
9      pooja.kapoor718@rediffmail.com
10        deepak.singh133@hotmail.com
11        aarav.sharma565@hotmail.com
12        krishna.sharma641@gmail.com
13         karan.desai251@outlook.com
14         sanjay.kapoor404@gmail.com
15         sneha.joshi855@hotmail.com
16        ramesh.gupta920@hotmail.com
17           arjun.bhatt340@yahoo.com
18           ayaan.desai320@yahoo.com
19           pooja.singh721@gmail.com
20           sanjay.iyer731@yahoo.com
Name: contact_email, dtype: str

In [156]:
suppliers[~suppliers["contact_email"].str.contains("@", na=False)][["contact_email"]]

Empty DataFrame
Columns: [contact_email]
Index: []

In [157]:
suppliers[suppliers["rating"]>5]

Empty DataFrame
Columns: [supplier_id, supplier_name, city, contact_name, contact_email, contact_phone, rating]
Index: []

In [87]:
suppliers.to_csv("suppliers_cleaned.csv", index=False)

In [206]:
# Fact Invantory data cleaning
inventory.isnull().sum()

inventory_id           0
product_id             0
store_id               0
stock_quantity       311
reorder_level          0
last_restock_date      0
dtype: int64

In [210]:
inventory["stock_quantity"] = inventory["stock_quantity"].fillna(inventory["stock_quantity"].median())

In [211]:
inventory.isnull().sum()

inventory_id         0
product_id           0
store_id             0
stock_quantity       0
reorder_level        0
last_restock_date    0
dtype: int64

In [212]:
inventory.duplicated().sum()

np.int64(0)

In [213]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       9000 non-null   int64
 1   product_id         9000 non-null   int64
 2   store_id           9000 non-null   int64
 3   stock_quantity     9000 non-null   float64
 4   reorder_level      9000 non-null   int64
 5   last_restock_date  9000 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 422.0 KB

In [214]:
inventory.describe()

       inventory_id   product_id     store_id  stock_quantity  reorder_level
count   9000.000000  9000.000000  9000.000000     9000.000000    9000.000000
mean    4500.500000   372.033222    37.342111      477.787111      85.503333
std     2598.220545  1363.542098   136.184044      295.586791      37.804366
min        1.000000     1.000000     1.000000      -50.000000      20.000000
25%     2250.750000    91.750000    10.000000      224.000000      53.000000
50%     4500.500000   184.000000    19.000000      477.000000      86.000000
75%     6750.250000   275.000000    27.000000      729.250000     118.000000
max     9000.000000  9999.000000   999.000000     1000.000000     150.000000

In [215]:
inventory["last_restock_date"] = pd.to_datetime(inventory["last_restock_date"])

In [216]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       9000 non-null   int64
 1   product_id         9000 non-null   int64
 2   store_id           9000 non-null   int64
 3   stock_quantity     9000 non-null   float64
 4   reorder_level      9000 non-null   int64
 5   last_restock_date  9000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(4)
memory usage: 422.0 KB

In [217]:
inventory[inventory["stock_quantity"] < 0]

,inventory_id,product_id,store_id,stock_quantity,reorder_level,last_restock_date
35,36,234,5,-13.0,63,2023-06-25
93,94,281,1,-15.0,45,2023-01-26
94,95,32,12,-13.0,119,2024-07-26
103,104,242,35,-22.0,34,2023-06-10
123,124,9999,999,-38.0,95,2024-01-03
...,...,...,...,...,...,...
8879,8880,9999,999,-36.0,89,2023-02-09
8899,8900,39,26,-14.0,56,2023-03-28
8917,8918,135,10,-24.0,31,2024-11-12
8921,8922,171,30,-6.0,27,2024-07-14
8952,8953,9999,999,-7.0,34,2023-09-30

In [6]:
inventory.loc[inventory["stock_quantity"] < 0, "stock_quantity"] = 0

In [7]:
inventory[inventory["stock_quantity"] < 0]

Empty DataFrame
Columns: [inventory_id, product_id, store_id, stock_quantity, reorder_level, last_restock_date]
Index: []

In [8]:
inventory.describe()

       inventory_id   product_id     store_id  stock_quantity  reorder_level
count   9000.000000  9000.000000  9000.000000     8689.000000    9000.000000
mean    4500.500000   372.033222    37.342111      478.841869      85.503333
std     2598.220545  1363.542098   136.184044      299.134914      37.804366
min        1.000000     1.000000     1.000000        0.000000      20.000000
25%     2250.750000    91.750000    10.000000      213.000000      53.000000
50%     4500.500000   184.000000    19.000000      477.000000      86.000000
75%     6750.250000   275.000000    27.000000      739.000000     118.000000
max     9000.000000  9999.000000   999.000000     1000.000000     150.000000

In [9]:
inventory["stock_quantity"].isnull().sum()

np.int64(311)

In [10]:
inventory["stock_quantity"] = inventory["stock_quantity"].fillna(inventory["stock_quantity"].median())

In [11]:
inventory.describe()

       inventory_id   product_id     store_id  stock_quantity  reorder_level
count   9000.000000  9000.000000  9000.000000     9000.000000    9000.000000
mean    4500.500000   372.033222    37.342111      478.778222      85.503333
std     2598.220545  1363.542098   136.184044      293.920698      37.804366
min        1.000000     1.000000     1.000000        0.000000      20.000000
25%     2250.750000    91.750000    10.000000      224.000000      53.000000
50%     4500.500000   184.000000    19.000000      477.000000      86.000000
75%     6750.250000   275.000000    27.000000      729.250000     118.000000
max     9000.000000  9999.000000   999.000000     1000.000000     150.000000

In [12]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       9000 non-null   int64
 1   product_id         9000 non-null   int64
 2   store_id           9000 non-null   int64
 3   stock_quantity     9000 non-null   float64
 4   reorder_level      9000 non-null   int64
 5   last_restock_date  9000 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 422.0 KB

In [13]:
inventory["last_restock_date"] = pd.to_datetime(inventory["last_restock_date"])

In [14]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       9000 non-null   int64
 1   product_id         9000 non-null   int64
 2   store_id           9000 non-null   int64
 3   stock_quantity     9000 non-null   float64
 4   reorder_level      9000 non-null   int64
 5   last_restock_date  9000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(4)
memory usage: 422.0 KB

In [15]:
inventory.to_csv("inventory_cleaned.csv", index=False)

In [16]:
#  clean data of inventory movement
inventory_movement.isnull().sum()

movement_id               0
product_id                0
store_id                  0
movement_type             0
quantity                  0
movement_date             0
reference_order_id    11648
dtype: int64

In [17]:
inventory_movement.info()

<class 'pandas.DataFrame'>
RangeIndex: 26000 entries, 0 to 25999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   movement_id         26000 non-null  int64
 1   product_id          26000 non-null  int64
 2   store_id            26000 non-null  int64
 3   movement_type       26000 non-null  str
 4   quantity            26000 non-null  int64
 5   movement_date       26000 non-null  str
 6   reference_order_id  14352 non-null  float64
dtypes: float64(1), int64(4), str(2)
memory usage: 1.4 MB

In [25]:
inventory_movement["movement_date"] = pd.to_datetime(inventory_movement["movement_date"])

In [26]:
inventory_movement.info()

<class 'pandas.DataFrame'>
RangeIndex: 26000 entries, 0 to 25999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   movement_id         26000 non-null  int64
 1   product_id          26000 non-null  int64
 2   store_id            26000 non-null  int64
 3   movement_type       26000 non-null  str
 4   quantity            26000 non-null  int64
 5   movement_date       26000 non-null  datetime64[us]
 6   reference_order_id  14352 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(4), str(1)
memory usage: 1.4 MB

In [ ]:
# missing values
# reference_order_id contains valid missing values.
# No imputation required because not every inventory movement has an associated order.

In [28]:
# check invalid quantity
inventory_movement[inventory_movement["quantity"] <=0]

,movement_id,product_id,store_id,movement_type,quantity,movement_date,reference_order_id
77,78,244,7,IN,0,2023-03-05,NaN
106,107,197,16,OUT,0,2024-05-25,9780.0
133,134,8888,888,OUT,0,2023-07-12,888888.0
158,159,8888,888,IN,0,2024-02-05,NaN
164,165,8888,888,OUT,0,2023-03-16,888888.0
...,...,...,...,...,...,...,...
25787,25788,8888,888,OUT,0,2023-07-04,888888.0
25891,25892,266,7,OUT,0,2023-09-01,11547.0
25913,25914,8888,888,OUT,0,2023-04-07,888888.0
25933,25934,8888,888,IN,0,2023-09-04,NaN
25964,25965,324,19,OUT,0,2024-02-07,43.0

In [29]:
inventory_movement[inventory_movement["quantity"] <=0].shape

(804, 7)

In [30]:
# Remove rows where quantity is 0 or less
inventory_movement = inventory_movement[inventory_movement["quantity"] > 0]

In [31]:
inventory_movement[inventory_movement["quantity"] <=0].shape

(0, 7)

In [32]:
inventory_movement.shape

(25196, 7)

In [33]:
inventory_movement.describe()

,movement_id,product_id,store_id,quantity,movement_date,reference_order_id
count,25196.000000,25196.000000,25196.000000,25196.000000,25196,13887.000000
mean,13003.862319,180.636728,18.044571,250.461145,2023-12-31 17:35:49.484045,15165.436883
min,1.000000,1.000000,1.000000,1.000000,2023-01-01 00:00:00,4.000000
25%,6496.750000,89.000000,9.000000,126.000000,2023-07-02 00:00:00,7793.000000
50%,13002.500000,181.000000,18.000000,250.000000,2023-12-31 00:00:00,15158.000000
75%,19509.250000,272.000000,27.000000,375.000000,2024-07-01 00:00:00,22588.500000
max,26000.000000,360.000000,35.000000,500.000000,2024-12-31 00:00:00,30000.000000
std,7509.526271,104.481951,10.136283,144.241351,NaN,8626.828245

In [34]:
inventory_movement["movement_date"].isnull().sum()

np.int64(0)

In [35]:
inventory_movement.info()

<class 'pandas.DataFrame'>
Index: 25196 entries, 0 to 25999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   movement_id         25196 non-null  int64
 1   product_id          25196 non-null  int64
 2   store_id            25196 non-null  int64
 3   movement_type       25196 non-null  str
 4   quantity            25196 non-null  int64
 5   movement_date       25196 non-null  datetime64[us]
 6   reference_order_id  13887 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(4), str(1)
memory usage: 1.5 MB

In [25]:
inventory_movement.isnull().sum()

movement_id               0
product_id                0
store_id                  0
movement_type             0
quantity                  0
movement_date             0
reference_order_id    11648
dtype: int64

In [26]:
inventory_movement["reference_order_id"].isnull().sum()

np.int64(11648)

In [30]:
inventory_movement.columns

Index(['movement_id', 'product_id', 'store_id', 'movement_type', 'quantity',
       'movement_date', 'reference_order_id'],
      dtype='str')

In [31]:
inventory_movement.groupby("movement_type")["reference_order_id"].apply(
    lambda x: x.isnull().sum()
)

movement_type
IN     11648
OUT        0
Name: reference_order_id, dtype: int64

In [36]:
inventory_movement.to_csv("inventory_movement_cleaned.csv", index=False)

In [37]:
# data clean of sales order items csv files
sales_order_items.isnull().sum()

order_item_id             0
order_id                  0
product_id                0
quantity                  0
unit_price_inr            0
discount_amount_inr    1494
line_total_inr            0
dtype: int64

In [38]:
sales_order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_item_id        48000 non-null  int64
 1   order_id             48000 non-null  int64
 2   product_id           48000 non-null  int64
 3   quantity             48000 non-null  int64
 4   unit_price_inr       48000 non-null  float64
 5   discount_amount_inr  46506 non-null  float64
 6   line_total_inr       48000 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 2.6 MB

In [45]:
sales_order_items.rename(columns = {'unit_price_inr':'unit_price'}, inplace=True)

In [44]:
sales_order_items.rename(columns = {'discount_amount_inr':'discount_amount'}, inplace=True)

In [46]:
sales_order_items.rename(columns = {'line_total_inr':' line_total'}, inplace=True)

In [47]:
sales_order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    48000 non-null  int64
 1   order_id         48000 non-null  int64
 2   product_id       48000 non-null  int64
 3   quantity         48000 non-null  int64
 4   unit_price       48000 non-null  float64
 5   discount_amount  46506 non-null  float64
 6    line_total      48000 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 2.6 MB

In [48]:
sales_order_items["discount_amount"] = sales_order_items["discount_amount"].fillna(0)

In [49]:
sales_order_items.describe()

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount,line_total
count,48000.000000,48000.000000,48000.000000,48000.000000,48000.000000,48000.00000,48000.000000
mean,24000.500000,34924.164458,378.086687,5.172479,7528.547799,6011.44822,39014.702662
std,13856.550797,138646.872188,1383.359384,3.428316,4337.499260,6893.94790,44041.683669
min,1.000000,1.000000,1.000000,-10.000000,20.910000,0.00000,18.360000
25%,12000.750000,7720.000000,92.000000,3.000000,3774.162500,1052.41750,11175.222500
50%,24000.500000,15464.000000,184.000000,5.000000,7524.385000,3428.84000,27924.280000
75%,36000.250000,23023.250000,276.000000,8.000000,11291.792500,8550.84250,54666.520000
max,48000.000000,999999.000000,9999.000000,10.000000,14999.960000,43354.37000,764469.320000

In [51]:
sales_order_items[sales_order_items["quantity"] < 0]

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount,line_total
6,7,999999,9999,-4,501.01,513.07,7190.08
17,18,2807,59,-8,13042.69,5628.03,492523.18
73,74,999999,9999,-7,7256.99,4258.71,168379.63
91,92,999999,9999,-9,1402.69,3095.12,40526.57
132,133,999999,9999,-5,6313.78,2465.70,147620.10
...,...,...,...,...,...,...,...
47858,47859,999999,9999,-7,26.92,35.58,655.55
47876,47877,999999,9999,-7,8931.82,284.66,314766.57
47964,47965,6074,267,-10,1134.89,541.28,58270.37
47980,47981,999999,9999,-1,2486.11,307.82,8867.96
47998,47999,18956,342,-2,2128.73,1261.13,14052.12

In [6]:
sales_order_items['product_id'].isin(products['product_id']).value_counts()

product_id
True     47033
False      967
Name: count, dtype: int64

In [26]:
sales_order_items = sales_order_items[sales_order_items["quantity"] >= 0]

,order_item_id,order_id,product_id,quantity,unit_price_inr,discount_amount_inr,line_total_inr
0,1,3615,116,2,14748.96,6365.16,23132.76
1,2,638,121,7,7436.79,9629.47,42428.06
2,3,11609,114,9,7159.53,17796.38,46639.39
3,4,8136,242,5,13497.06,14168.03,53317.27
4,5,12988,297,6,9701.43,6303.55,51905.03
...,...,...,...,...,...,...,...
47994,47995,14172,259,6,7587.96,11331.98,34195.78
47995,47996,16814,338,10,14501.73,1689.14,143328.16
47996,47997,24860,204,7,4839.82,4496.70,29382.04
47997,47998,15419,304,7,6159.60,650.05,42467.15
47999,48000,18268,121,8,13433.55,4808.61,102659.79

In [65]:
sales_order_items[sales_order_items["quantity"] < 0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price_inr, discount_amount_inr, line_total_inr]
Index: []

In [66]:
sales_order_items.describe()

,order_item_id,order_id,product_id,quantity,unit_price_inr,discount_amount_inr,line_total_inr
count,46564.000000,46564.000000,46564.000000,46564.000000,46564.000000,45132.000000,46564.000000
mean,23981.947663,15090.807534,180.219569,5.502684,7527.231702,6204.892831,35239.654850
std,13847.996206,8667.724604,103.818383,2.866361,4337.259980,6922.915060,29656.828892
min,1.000000,1.000000,1.000000,1.000000,20.910000,0.050000,18.360000
25%,11992.750000,7556.000000,90.000000,3.000000,3772.977500,1211.035000,10890.897500
50%,23957.500000,15155.500000,180.000000,6.000000,7524.385000,3625.865000,27009.435000
75%,35954.250000,22571.000000,270.000000,8.000000,11288.772500,8811.015000,52678.445000
max,48000.000000,29999.000000,360.000000,10.000000,14999.960000,43354.370000,148592.430000

In [31]:
 sales_order_items["quantity"].abs()

0         2
1         7
2         9
3         5
4         6
         ..
47994     6
47995    10
47996     7
47997     7
47999     8
Name: quantity, Length: 46564, dtype: int64

In [56]:
sales_order_items["product_id"].nunique()

360

In [57]:
sales_order_items[
    ~sales_order_items["product_id"].isin(products["product_id"])
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_amount,  line_total]
Index: []

In [59]:
# file names
%who

categories	 customers	 inventory	 inventory_movement	 np	 pd	 products	 sales_order_items	 sales_orders
stores	 suppliers

In [67]:
sales_order_items.describe()

,order_item_id,order_id,product_id,quantity,unit_price_inr,discount_amount_inr,line_total_inr
count,46564.000000,46564.000000,46564.000000,46564.000000,46564.000000,45132.000000,46564.000000
mean,23981.947663,15090.807534,180.219569,5.502684,7527.231702,6204.892831,35239.654850
std,13847.996206,8667.724604,103.818383,2.866361,4337.259980,6922.915060,29656.828892
min,1.000000,1.000000,1.000000,1.000000,20.910000,0.050000,18.360000
25%,11992.750000,7556.000000,90.000000,3.000000,3772.977500,1211.035000,10890.897500
50%,23957.500000,15155.500000,180.000000,6.000000,7524.385000,3625.865000,27009.435000
75%,35954.250000,22571.000000,270.000000,8.000000,11288.772500,8811.015000,52678.445000
max,48000.000000,29999.000000,360.000000,10.000000,14999.960000,43354.370000,148592.430000

In [68]:
sales_order_items["discount_amount_inr"] = sales_order_items["discount_amount_inr"].fillna(0)

In [69]:
sales_order_items.describe()

,order_item_id,order_id,product_id,quantity,unit_price_inr,discount_amount_inr,line_total_inr
count,46564.000000,46564.000000,46564.000000,46564.000000,46564.000000,46564.000000,46564.000000
mean,23981.947663,15090.807534,180.219569,5.502684,7527.231702,6014.071456,35239.654850
std,13847.996206,8667.724604,103.818383,2.866361,4337.259980,6899.307941,29656.828892
min,1.000000,1.000000,1.000000,1.000000,20.910000,0.000000,18.360000
25%,11992.750000,7556.000000,90.000000,3.000000,3772.977500,1053.590000,10890.897500
50%,23957.500000,15155.500000,180.000000,6.000000,7524.385000,3427.435000,27009.435000
75%,35954.250000,22571.000000,270.000000,8.000000,11288.772500,8560.612500,52678.445000
max,48000.000000,29999.000000,360.000000,10.000000,14999.960000,43354.370000,148592.430000

In [33]:
sales_order_items.to_csv("sales_order_items_cleaned.csv", index=False)

In [9]:
sales_order_items[
    ~sales_order_items['product_id'].isin(products['product_id'])
]

,order_item_id,order_id,product_id,quantity,unit_price_inr,discount_amount_inr,line_total_inr
6,7,999999,9999,-4,501.01,513.07,7190.08
73,74,999999,9999,-7,7256.99,4258.71,168379.63
91,92,999999,9999,-9,1402.69,3095.12,40526.57
132,133,999999,9999,-5,6313.78,2465.70,147620.10
156,157,999999,9999,-3,10379.07,1572.72,125076.90
...,...,...,...,...,...,...,...
47738,47739,999999,9999,-5,1893.28,2477.02,41260.57
47801,47802,999999,9999,-4,3025.40,234.36,48635.53
47858,47859,999999,9999,-7,26.92,35.58,655.55
47876,47877,999999,9999,-7,8931.82,284.66,314766.57
47980,47981,999999,9999,-1,2486.11,307.82,8867.96

In [12]:
sales_order_items[
    ~sales_order_items['product_id'].isin(products['product_id'])
]['product_id'].unique()

array([], dtype=int64)

In [11]:
sales_order_items = sales_order_items[
    sales_order_items['product_id'] != 9999
]

In [10]:
sales_order_items['product_id'].isin(products['product_id']).value_counts()

product_id
True     47033
False      967
Name: count, dtype: int64

In [14]:
(sales_order_items["quantity"]<0).sum()

np.int64(469)

In [15]:
sales_order_items["discount_amount_inr"].isnull().sum()

np.int64(0)

In [16]:
sales_order_items["discount_amount_inr"] = sales_order_items["discount_amount_inr"].fillna(0)

In [17]:
sales_order_items["discount_amount_inr"].isnull().sum()

np.int64(0)

In [20]:
sales_order_items["quantity"] = sales_order_items["quantity"].abs()

In [21]:
(sales_order_items["quantity"] < 0).sum()

np.int64(0)

In [24]:
print("Negative quantities:", (sales_order_items["quantity"] < 0).sum())
print("Minimum quantity:", sales_order_items["quantity"].min())

Negative quantities: 0
Minimum quantity: 1

In [23]:
sales_order_items.to_csv("sales_order_items_cleaned.csv", index=False)

In [71]:
# clean data of sales orders csv file
sales_orders.isnull().sum()

order_id              0
customer_id           0
store_id              0
order_date            0
payment_method        0
order_status          0
discount_pct          0
total_amount_inr    873
dtype: int64

In [74]:
sales_orders.rename(columns = {'total_amount_inr':'total_amount'})

,order_id,customer_id,store_id,order_date,payment_method,order_status,discount_pct,total_amount
0,1,1150,5,2024-03-21,Debit Card,Completed,5,13661.37
1,2,2815,12,2024-06-06,Debit Card,Completed,5,16041.50
2,3,3345,11,2024-04-18,Net Banking,Completed,25,16927.23
3,4,1737,20,2023-04-11,UPI,Cancelled,5,20767.47
4,5,845,35,2023-08-03,UPI,Pending,5,7295.72
...,...,...,...,...,...,...,...,...
30295,11750,1596,6,2024-08-22,Credit Card,Completed,0,1454.29
30296,23643,3981,21,2023-12-21,Credit Card,Completed,0,17322.39
30297,29983,5951,20,2023-09-25,Credit Card,Returned,10,16405.78
30298,18695,1980,30,2024-03-25,Net Banking,Cancelled,0,20962.58
30299,545,1501,33,2024-04-09,UPI,Completed,25,12134.08

In [75]:
sales_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 30300 entries, 0 to 30299
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          30300 non-null  int64
 1   customer_id       30300 non-null  int64
 2   store_id          30300 non-null  int64
 3   order_date        30300 non-null  str
 4   payment_method    30300 non-null  str
 5   order_status      30300 non-null  str
 6   discount_pct      30300 non-null  int64
 7   total_amount_inr  29427 non-null  float64
dtypes: float64(1), int64(4), str(3)
memory usage: 1.8 MB

In [76]:
sales_orders.duplicated().sum()

np.int64(300)

In [77]:
sales_orders = sales_orders.drop_duplicates()

In [78]:
sales_orders["total_amount_inr"] = sales_orders["total_amount_inr"].fillna(sales_orders["total_amount_inr"].median())

In [79]:
sales_orders["order_date"] = pd.to_datetime(sales_orders["order_date"])

In [80]:
sales_orders.dtypes

order_id                     int64
customer_id                  int64
store_id                     int64
order_date          datetime64[us]
payment_method                 str
order_status                   str
discount_pct                 int64
total_amount_inr           float64
dtype: object

In [81]:
sales_orders.isnull().sum()

order_id            0
customer_id         0
store_id            0
order_date          0
payment_method      0
order_status        0
discount_pct        0
total_amount_inr    0
dtype: int64

In [82]:
sales_orders.duplicated().sum()

np.int64(0)

In [83]:
sales_orders.describe()

,order_id,customer_id,store_id,order_date,discount_pct,total_amount_inr
count,30000.000000,30000.000000,30000.000000,30000,30000.000000,30000.000000
mean,15000.500000,4857.725067,36.760967,2023-12-31 15:54:40.320000,12.287133,11852.519165
min,1.000000,1.000000,1.000000,2023-01-01 00:00:00,0.000000,-24884.050000
25%,7500.750000,1517.000000,9.000000,2023-07-01 00:00:00,0.000000,5985.335000
50%,15000.500000,3047.500000,18.000000,2024-01-01 00:00:00,10.000000,12184.695000
75%,22500.250000,4571.000000,27.000000,2024-07-01 00:00:00,20.000000,18385.770000
max,30000.000000,99999.000000,999.000000,2024-12-31 00:00:00,150.000000,24998.800000
std,8660.398374,13433.534445,135.122837,NaN,20.000124,8202.577014

In [84]:
sales_orders[sales_orders["total_amount_inr"] < 0]

,order_id,customer_id,store_id,order_date,payment_method,order_status,discount_pct,total_amount_inr
22,23,123,25,2023-11-05,Cash,Completed,108,-15434.37
26,27,99999,999,2023-09-11,Wallet,Completed,105,-5737.85
55,56,99999,999,2023-05-03,Debit Card,Pending,87,-11671.31
160,161,99999,999,2023-02-13,Net Banking,Completed,83,-21992.70
167,168,99999,999,2024-12-05,Credit Card,Completed,102,-18566.44
...,...,...,...,...,...,...,...,...
29758,29759,99999,999,2023-10-27,UPI,Completed,132,-5041.12
29817,29818,99999,999,2024-08-06,Cash,Completed,117,-8129.76
29834,29835,2965,22,2024-06-18,UPI,Completed,101,-13501.47
29941,29942,4536,12,2023-01-04,Debit Card,Completed,88,-24426.44
29956,29957,99999,999,2024-12-25,Net Banking,Completed,125,-9012.79

In [85]:
sales_orders[sales_orders["total_amount_inr"] < 0].shape[0]

844

In [86]:
sales_orders = sales_orders[sales_orders["total_amount_inr"] >= 0]

In [87]:
sales_orders["total_amount_inr"] = sales_orders["total_amount_inr"].abs()

In [88]:
sales_orders.describe()

,order_id,customer_id,store_id,order_date,discount_pct,total_amount_inr
count,29156.000000,29156.000000,29156.000000,29156,29156.000000,29156.000000
mean,14993.943785,3047.963404,18.428660,2024-01-01 02:47:08.042255,9.344286,12562.297442
min,1.000000,1.000000,1.000000,2023-01-01 00:00:00,0.000000,150.270000
25%,7503.750000,1486.000000,9.000000,2023-07-02 00:00:00,0.000000,6566.132500
50%,14990.500000,2999.000000,18.000000,2024-01-01 12:00:00,5.000000,12184.695000
75%,22490.250000,4497.000000,27.000000,2024-07-02 00:00:00,15.000000,18573.435000
max,30000.000000,99999.000000,999.000000,2024-12-31 00:00:00,148.000000,24998.800000
std,8658.435280,2856.656160,25.100378,NaN,9.617308,7059.191139

In [89]:
sales_orders[sales_orders["discount_pct"] > 100]

,order_id,customer_id,store_id,order_date,payment_method,order_status,discount_pct,total_amount_inr
1382,1383,99999,999,2024-12-10,UPI,Cancelled,136,12184.695
6736,6737,99999,999,2023-07-23,Cash,Completed,123,12184.695
8148,8149,1239,25,2024-08-11,Debit Card,Completed,133,12184.695
8872,8873,99999,999,2023-05-13,Credit Card,Completed,130,12184.695
9507,9508,99999,999,2023-05-25,Credit Card,Completed,110,12184.695
10955,10956,99999,999,2023-09-05,Net Banking,Completed,141,12184.695
13749,13750,863,33,2023-06-05,Cash,Completed,148,12184.695
14764,14765,99999,999,2023-03-23,Net Banking,Completed,103,12184.695
16341,16342,99999,999,2024-05-12,Credit Card,Completed,127,12184.695
17934,17935,99999,999,2024-07-15,Credit Card,Completed,124,12184.695
19404,19405,99999,999,2023-03-09,Cash,Pending,128,12184.695
21056,21057,99999,999,2024-02-20,Wallet,Completed,143,12184.695
21971,21972,99999,999,2024-07-25,Credit Card,Cancelled,128,12184.695
24378,24379,4221,29,2024-04-24,Net Banking,Pending,113,12184.695
25506,25507,99999,999,2024-02-28,Wallet,Pending,147,12184.695
27925,27926,1546,9,2024-01-03,Net Banking,Completed,144,12184.695

In [90]:
sales_orders[sales_orders["discount_pct"] > 100].shape[0]

16

In [91]:
sales_orders = sales_orders[sales_orders["discount_pct"] <= 100]

In [95]:
#sales_orders.isnull().sum()
#sales_orders.duplicated().sum()
sales_orders.describe()

,order_id,customer_id,store_id,order_date,discount_pct,total_amount_inr
count,29140.000000,29140.000000,29140.000000,29140,29140.000000,29140.000000
mean,14993.643823,3008.186822,18.024091,2024-01-01 02:57:09.512697,9.278106,12562.504773
min,1.000000,1.000000,1.000000,2023-01-01 00:00:00,0.000000,150.270000
25%,7501.750000,1486.000000,9.000000,2023-07-02 00:00:00,0.000000,6563.125000
50%,14990.500000,2998.000000,18.000000,2024-01-01 00:00:00,5.000000,12184.695000
75%,22491.250000,4496.000000,27.000000,2024-07-02 00:00:00,15.000000,18575.600000
max,30000.000000,99999.000000,999.000000,2024-12-31 00:00:00,97.000000,24998.800000
std,8659.094235,2071.735057,15.304349,NaN,9.190788,7061.123399

In [102]:
sales_orders['total_amount_inr'].sum()

np.float64(366071389.09000003)

In [103]:
sales_orders['total_amount_inr'].describe()

count    29140.000000
mean     12562.504773
std       7061.123399
min        150.270000
25%       6563.125000
50%      12184.695000
75%      18575.600000
max      24998.800000
Name: total_amount_inr, dtype: float64

In [99]:
sales_orders.to_csv("sales_orders_cleaned.csv", index=False)